# Generated by Django 3.0.2 on 2020-02-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organisation',
        ),
    ]
