# Generated by Django 3.0.2 on 2020-02-22 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_remove_customuser_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=13),
        ),
    ]
